# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SimpleSoundWaves
email: moxxy@simplesoundwaves.com
description: >- # this means to ignore newlines until "baseurl:"
  I am a musician and an engineer. I design and implement music and technology together to help others learn, teach, enjoy and be inspired; this is very important to my value system. My experience in producing, technology, teaching and learning fosters creative artistic expressions and installations, together with systems thinking, mindfulness, contemporary art, music, musicology, artistic performance and technology. I excel at being on both sides of the creative design process.
baseurl: "ssw_blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SmplSndWvs
github_username: ddrenk

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
